### ISSUE TITLE
Columns are misaligned

### ISSUE THREAD

**Issue by rmariuzzo** [energydrink9/functional-data-grid#22]
The current demo at: https://energydrink9.github.io/functional-data-grid-examples shows the following issue (which is not easily visible since the cell contents is center aligned):

<img width="293" alt="screen shot 2018-12-04 at 5 34 11 pm" src="https://user-images.githubusercontent.com/439839/49481121-c6dea000-f7ff-11e8-9257-c0d292960b03.png">

In a project I applied a workaround by setting each header: `box-sizing: border-box`. The solution would be to correctly calculated column width taking in account padding and/or borders.

**Comment by energydrink9** [comment]
Hi Rubens,
Thank you for your reporting this issue
The problem has been fixed taking into account the scrollbar width of the grid's body
Let me know if you encounter some other problem

**Comment by rmariuzzo** [comment]
Thank you @energydrink9! That was fast!

**Comment by rmariuzzo** [comment]
Hey @energydrink9! Looks like I still need to add:
```css
.functional-data-grid__row__free > div {
  box-sizing: border-box;
}
```
To make it work. The demo have this property set with a global selector. I consider to add `box-sizing: border-box` to the default style of the header cols. wdyt?

**Comment by energydrink9** [comment]
Hi Rubens,

functional-data-grid is designed to work with the default box-sizing set to border-box.
I've just made a commit that sets the box-sizing to border-box in the grid and in its children

**Comment by rmariuzzo** [comment]
Great!
